name: Output Issues Project
on: 
  issues:
    types: opened
jobs:
  output-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Output details
        run: echo "${{ toJson(github.event_name) }}"
